using System;
using PasswordGenerator;

class Program
{
    static void Main()
    {
        Console.WriteLine("What is your name? ");

        var name = Console.ReadLine();

        var currDate = DateTime.Now;

        Console.WriteLine($"{Environment.NewLine}Hello, {name}, on {currDate:d}");
        // Console.ReadKey(true);



        var pwd = new Password();
        var password = pwd.Next();
        Console.WriteLine("Your password autogenerated is: " + password.ToString() + " with nuGet provided Package ");

    }
}
